version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reseautage
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: reseautage
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app_network
    volumes:
      - ./backend:/usr/src/app

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
