version: '3.8'

services:
  # Service MySQL
  database:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  # Service Backend Node.js
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projetdb
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app_network
    volumes:
      - ./backend:/usr/src/app

  # Service Frontend Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  # Service Adminer
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
